//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mileage_Tracker.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RunningEntities : DbContext
    {
        public RunningEntities()
            : base("name=RunningEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Meet> Meets { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RunningCalendar> RunningCalendars { get; set; }
        public virtual DbSet<RunType> RunTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WeeklyPercnet> WeeklyPercnets { get; set; }
        public virtual DbSet<WeeklyPlan> WeeklyPlans { get; set; }
    }
}
