//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mileage_Tracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunningCalendar
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Monday { get; set; }
        public double Distance { get; set; }
        public int RunType { get; set; }
        public string Notes { get; set; }
    
        public virtual RunType RunType1 { get; set; }
        public virtual User User { get; set; }
    }
}
